name: pilisp_cli
description: Shared code for running a rudimentary command-line interface to the PiLisp programming language.
version: 1.0.0-alpha.13
repository: https://github.com/pilisp/pilisp-cli

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.4.0
  async: ^2.11.0
  chalkdart: ^2.0.9
  js: ^0.6.7
  pilisp: ^1.0.0-alpha.12

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
